openapi: 3.0.0
info:
  title: Cadastro
  description: 'Getting started with Laravel and Swagger'
  termsOfService: ''
  contact:
    email: jsauzem@gmail.com
  version: 1.0.0
paths:
  /register/user:
    post:
      summary: 'Create users'
      description: 'Create users'
      requestBody:
        description: 'Paramaters create Users'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/postCadastro'
      responses:
        '201':
          description: 'A list with users'
        '400':
          description: 'fail! create users'
components:
  schemas:
    postCadastro:
      required:
        - name
        - cpf_cnpj
        - email
        - password
        - type_users_id
      properties:
        name:
          type: string
        cpf_cnpj:
          type: integer
        email:
          type: string
        password:
          type: float
        type_users_id:
          type: integer
      type: object
